### ISSUE TITLE
The bracket is missing

### ISSUE THREAD

**Issue by buronbekdev** [Munzir-1303/Responsif#1]
https://github.com/Munzir-1303/Responsif/blob/0d432df74317aa7230371dd0d5d2c79d5ccaa8d3/main/main.css#L71

Munzir has a parenthesis in line 71, please correct it

**Comment by buronpro** [comment]
Hi Buronpro, bye👍

**Comment by Munzir-1303** [comment]
Hi Buronpro, bye😎
